const express = require("express");
const app = express();
const cors = require("cors");
const PORT = process.env.PORT || 3000;

// Enable CORS for all routes and origins
app.use(cors());

app.get("/truisms/:type/:number?", (req, res) => {
  const { type, number } = req.params;

  // Default to 1 if number isn't specified or is invalid
  let numTruisms = parseInt(number) || 1;
  // clamp the number of truisms to be between 1 and 100
  numTruisms = Math.min(Math.max(numTruisms, 1), 100);

  // Select the list of truisms based on the type provided in the route
  switch (type) {
    case "jh":
      selectedTruismsList = JHTruisms;
      break;
    case "airbnb":
      selectedTruismsList = airBnbTruisms;
      break;
    default:
      selectedTruismsList = JHTruisms;
  }
  // Check if the type is valid, should always be because of default case above
  if (!selectedTruismsList) {
    return res.status(404).json({ error: "Truism type not found" });
  }

  // Function to get 'n' random elements from an array
  const getRandomTruisms = (list, num) => {
    const shuffled = [...list].sort(() => 0.5 - Math.random());
    return shuffled.slice(0, num);
  };

  const results = getRandomTruisms(selectedTruismsList, numTruisms);

  // const getRandomElements = (arr, n) => {
  //   let result = new Array(n),
  //     len = arr.length,
  //     taken = new Array(len);
  //   if (n > len)
  //     throw new RangeError(
  //       "getRandomElements: more elements taken than available"
  //     );

  //   while (n--) {
  //     const x = Math.floor(Math.random() * len);
  //     result[n] = arr[x in taken ? taken[x] : x];
  //     taken[x] = --len in taken ? taken[len] : len;
  //   }
  //   return result;
  // };

  // Get 'numTruisms' random truisms from the selected list
  // const results = getRandomElements(selectedTruismsList, numTruisms);

  res.json({ truisms: results });
});

app.get("/airbnb", (req, res) => {
  const randomIndex = Math.floor(Math.random() * airBnbTruisms.length);
  const randomTruism = airBnbTruisms[randomIndex];
  res.json({ truism: randomTruism });
});

app.get("/aphorism", (req, res) => {
  const n = parseInt(req.query.n, 10) || 1;
  const selectedAphorisms = selectRandomAphorisms(n); // Function to select 'n' random aphorisms
  res.json({ truisms: selectedAphorisms });
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});

const airBnbTruisms = [
  "DOORS HARBOR WHISPERS OF PAST TRAVELERS",
  "WINDOWS FRAME LONELY SUNSETS",
  "KEYS UNLOCK MOMENTS OF SOLITUDE",
  "WIFI SIGNALS TRANSMIT HIDDEN DESIRES",
  "BEDS ABSORB RESTLESSNESS",
  "WALLS ECHO SILENT SECRETS",
  "ARTWORK CONCEALS EMPTY SPACES",
  "TOWELS SOAK UP FLEETING PRESENCES",
  "CURTAINS SHIELD FRAGILE PRIVACY",
  "REVIEWS WHISPER OF PAST FOOTSTEPS",
  "LIGHT BULBS DIM BENEATH UNSEEN GAZE",
  "MIRRORS REFLECT FRAGMENTED IDENTITIES",
  "COFFEE CUPS HOLD BRIEF MORNING RITUALS",
  "PLANTS WILT AMIDST FORGOTTEN GREETINGS",
  "NOISES DISSOLVE IN THE WEARY NIGHT",
  "SOAP BARS BEAR TALES OF CLEANSING",
  "PAINTINGS HANG STILL IN VISUAL WHISPERS",
  "BLANKETS EMBRACE TRANSIENT WARMTH",
  "SHADOWS DANCE WITH UNCERTAINTY",
  "INVISIBLE LABOR SUSTAINS TEMPORARY COMFORT",
  "BOOKS SPEAK SILENTLY OF PASSED TIME",
  "DISHES BEAR WITNESS TO FLEETING APPETITES",
  "SHELVES HOLD FRAGMENTS OF ABSENT LIVES",
  "UNPACKING IS A TENDER LIE",
  "DOORBELLS CHIME THROUGH EMPTY HALLS",
  "RUGS CARRY FOOTSTEPS OF ANONYMITY",
  "MEMENTOS WHISPER OF FADING MEMORIES",
  "CANDLES FLICKER IN SUBDUED FLAMES",
  "CHAIRS REMAIN VACANT IN SILENCE",
  "STRIPPED BEDS ARE A RITUAL OF INDIGNITY",
  "MUSIC PLAYS TO EMPTY ROOMS",
  "NIGHT STANDS GUARD SLUMBERING SECRETS",
  "TEACUPS COOL BENEATH THE VEIL OF DUSK",
  "ALARMS AWAKEN LINGERING DREAMS",
  "WINDOWSILLS CRADLE FORGOTTEN TRINKETS",
  "CLOCKS TICK TO MARK VANISHING HOURS",
  "CLOSETS HOLD GHOSTS OF PAST ATTIRE",
  "RELAXATION MASKS TRUE INTENTIONS",
  "BATHROOM MIRRORS REVEAL MASKED IDENTITIES",
  "KEYBOARDS CLICK WITH DIGITAL ECHOES",
  "SMOKING AREAS VANISH IN SMOKE'S MEMORY",
  "REMOTE CONTROLS COMMAND FADED MEMORIES",
  "CUSHIONS BEAR WITNESS TO RESTLESSNESS",
  "TABLES REMAIN SET FOR IMAGINARY GATHERINGS",
  "THERMOSTATS CONTROL FLEETING COMFORT",
  "WINDOWSILLS BASK IN STRAY SUNBEAMS",
  "WINDOWS FRAME TEMPORARY REALITIES",
  "DOORS OPEN TO UNKNOWN WORLDS",
  "BEDS HOLD WEARY TRAVELER'S LAMENTS",
  "TOILETS SWALLOW WHISPERS OF VANITY",
  "LIGHTS CAST SHADOWS OF SLEEPLESSNESS",
  "WALLS WHISPER PREVIOUS GUESTS' TALES",
  "KEYS UNLOCK BRIEF SANCTUARIES",
  "WIFI CONNECTS TO ETHEREAL ROUTES",
  "ARTWORK MASKS EMPTY SPACES",
  "DOMESTICITY IS MADE INDUSTRIAL",
  "REVIEWS PAINT ILLUSIONS OF HOSPITALITY",
  "WINDOWSILLS BASK IN STRAY SUNBEAMS",
  "WARMTH IS ONLY EVER FOR RENT",
  "BATH MATS DROWN IN DRIPPING THOUGHTS",
  "PLUG SOCKETS WHISPER ELECTRIC PROMISES",
  "TV SCREENS DISPLAY TAMPERED WORLDS",
  "ARTIFICIAL PLANTS YEARNING FOR LIFE",
  "BALCONIES BREATHE WITH CITY'S PULSE",
  "CLOTHES HANGERS HOPE FOR OCCUPIED SPACE",
  "HALLWAYS ECHO FOOTSTEPS OF YESTERDAYS",
  "DUVET COVERS HOLD DREAMS OF RESTLESSNESS",
  "SHOWER GEL CAPTURES FLEETING FRAGRANCES",
  "GLASSES HOLD BLURRED MEMORIES",
  "CUTLERY CLINGS TO ECHOES OF MEALS",
  "CUSHION COVERS MASK UNSEEN TEARS",
  "TELEPHONE CORDS STRANDS OF DISCONNECTION",
  "SCENTED CANDLES BURN LONELY FLAMES",
  "WELCOME PACKETS BEAR SEASONED TALES",
  "FRIDGE MAGNETS CLING TO FADED SMILES",
  "HOUSEPLANTS REACH FOR PASSING GAZES",
  "FIREPLACES CRACKLE WITH FICTIONS",
  "BREAKFAST TRAYS HOLD CRUMBS OF HOSPITALITY",
  "EXIT SIGNS POINT TOWARD UNEXPECTED DEPARTURE",
  "ROBES WRAP SECRETS IN LUXURY",
  "SAFES GUARD TEMPORARY TREASURES",
  "DESK LAMPS BEAM SHADOWED REVELATIONS",
  "KETTLES WHISTLE SONGS OF TRANSIENCE",
  "CANDLE HOLDERS EMBRACE GLOWING MEMORIES",
  "LUGGAGE STANDS CARRY WEIGHTLESS BURDENS",
  "THERMOSTATS SETTLE TEMPERATURES OF EMOTION",
  "COASTERS BEAR RINGED TESTIMONIALS",
  "GPS GUIDES THROUGH UNCHARTED PASSAGES",
  "UMBRELLA STANDS HOLD SHADOWS OF RAIN",
  "SKYLIGHTS FILTER SUNLIGHT WHISPERS",
  "PICTURE FRAMES FRAME FRAGMENTS OF LIFE",
  "MINIMALISM MASKS A LACK OF ORIGINALITY",
  "WHITE NOISE MACHINES MUFFLE LONELINESS",
  "AUTHENTICITY IS A COMMODITY",
  "PLANTERS NURTURE HOPEFUL SEEDS",
  "LANDLINE PHONES RESOUND WITH SILENCE",
  "MAGAZINE RACKS BURST WITH UNTOUCHED STORIES",
  "BATHROBES EMBRACE FORLORN SOULS",
  "DISPOSAL BINS SWALLOW FORGOTTEN WASTE",
  "INFOTAINMENT SYSTEMS CARRY SUBDUED MELODIES",
  "WELCOME MATS WEAR FADED GREETINGS",
  "TISSUE BOXES COLLECT SHED TEARS",
  "SPICE RACKS SEASON ILLUSIONS OF HOME",
  "HANGERS DANGLE EMPTY ECHOES",
  "LAUNDRY BASKETS HOLD BURDENED LINENS",
  "INDOOR PLUNGE POOLS REFLECT REPOSED DREAMS",
  "TRASH BINS GATHER DISCARDED MOMENTS",
  "SOFA THROWS SWADDLE RESTLESSNESS",
  "HAND SOAP DISPENSERS CLEANSE UNTOLD SINS",
  "BATHROOM SCALES WEIGH UNSEEN BURDENS",
  "COAT HANGERS CARRY SHAPES OF FLESH",
  "MAGNIFYING MIRRORS ENLARGE FRAGILE VANITIES",
  "SHOWER CAPS SHIELD FRAGILE IDENTITIES",
  "WINE GLASSES RAISE TO ABSENT TOASTS",
  "BEDSIDE TABLES HOLD THOUGHTS IN STILLNESS",
  "LUXURY ROBES DRAPE OVER HIDDEN VULNERABILITIES",
];

const JHTruisms = [
  "A LITTLE KNOWLEDGE CAN GO A LONG WAY",
  "A LOT OF PROFESSIONALS ARE CRACKPOTS",
  "A MAN CAN'T KNOW WHAT IT IS TO BE A MOTHER",
  "A NAME MEANS A LOT JUST BY ITSELF",
  "A POSITIVE ATTITUDE MEANS ALL THE DIFFERENCE IN THE WORLD",
  "A RELAXED MAN IS NOT NECESSARILY A BETTER MAN",
  "A SENSE OF TIMING IS THE MARK OF GENIUS",
  "A SINCERE EFFORT IS ALL YOU CAN ASK",
  "A SINGLE EVENT CAN HAVE INFINITELY MANY INTERPRETATIONS",
  "A SOLID HOME BASE BUILDS A SENSE OF SELF",
  "A STRONG SENSE OF DUTY IMPRISONS YOU",
  "ABSOLUTE SUBMISSION CAN BE A FORM OF FREEDOM",
  "ABSTRACTION IS A TYPE OF DECADENCE",
  "ABUSE OF POWER COMES AS NO SURPRISE",
  "ACTION CAUSES MORE TROUBLE THAN THOUGHT",
  "ALIENATION PRODUCES ECCENTRICS OR REVOLUTIONARIES",
  "ALL THINGS ARE DELICATELY INTERCONNECTED",
  "AMBITION IS JUST AS DANGEROUS AS COMPLACENCY",
  "AMBIVALENCE CAN RUIN YOUR LIFE",
  "AN ELITE IS INEVITABLE",
  "ANGER OR HATE CAN BE A USEFUL MOTIVATING FORCE",
  "ANIMALISM IS PERFECTLY HEALTHY",
  "ANY SURPLUS IS IMMORAL",
  "ANYTHING IS A LEGITIMATE AREA OF INVESTIGATION",
  "ARTIFICIAL DESIRES ARE DESPOILING THE EARTH",
  "AT TIMES INACTIVITY IS PREFERABLE TO MINDLESS FUNCTIONING",
  "AT TIMES YOUR UNCONSCIOUSNESS IS TRUER THAN YOUR CONSCIOUS MIND",
  "AUTOMATION IS DEADLY",
  "AWFUL PUNISHMENT AWAITS REALLY BAD PEOPLE",
  "BAD INTENTIONS CAN YIELD GOOD RESULTS",
  "BEING ALONE WITH YOURSELF IS INCREASINGLY UNPOPULAR",
  "BEING HAPPY IS MORE IMPORTANT THAN ANYTHING ELSE",
  "BEING JUDGMENTAL IS A SIGN OF LIFE",
  "BEING SURE OF YOURSELF MEANS YOU'RE A FOOL",
  "BELIEVING IN REBIRTH IS THE SAME AS ADMITTING DEFEAT",
  "BOREDOM MAKES YOU DO CRAZY THINGS",
  "CALM IS MORE CONDUCTIVE TO CREATIVITY THAN IS ANXIETY",
  "CATEGORIZING FEAR IS CALMING",
  "CHANGE IS VALUABLE WHEN THE OPPRESSED BECOME TYRANTS",
  "CHASING THE NEW IS DANGEROUS TO SOCIETY",
  "CHILDREN ARE THE MOST CRUEL OF ALL",
  "CHILDREN ARE THE HOPE OF THE FUTURE",
  "CLASS ACTION IS A NICE IDEA WITH NO SUBSTANCE",
  "CLASS STRUCTURE IS AS ARTIFICIAL AS PLASTIC",
  "CONFUSING YOURSELF IS A WAY TO STAY HONEST",
  "CRIME AGAINST PROPERTY IS RELATIVELY UNIMPORTANT",
  "DECADENCE CAN BE AN END IN ITSELF",
  "DECENCY IS A RELATIVE THING",
  "DEPENDENCE CAN BE A MEAL TICKET",
  "DESCRIPTION IS MORE IMPORTANT THAN METAPHOR",
  "DEVIANTS ARE SACRIFICED TO INCREASE GROUP SOLIDARITY",
  "DISGUST IS THE APPROPRIATE RESPONSE TO MOST SITUATIONS",
  "DISORGANIZATION IS A KIND OF ANESTHESIA",
  "DON'T PLACE TOO MUCH TRUST IN EXPERTS",
  "DRAMA OFTEN OBSCURES THE REAL ISSUES",
  "DREAMING WHILE AWAKE IS A FRIGHTENING CONTRADICTION",
  "DYING AND COMING BACK GIVES YOU CONSIDERABLE PERSPECTIVE",
  "DYING SHOULD BE EASY AS FALLING OFF A LOG",
  "EATING TOO MUCH IS CRIMINAL",
  "ELABORATION IS A FORM OF POLLUTION",
  "EMOTIONAL RESPONSES ARE AS VALUABLE AS INTELLECTUAL RESPONSES",
  "ENJOY YOURSELF BECAUSE YOU CAN'T CHANGE ANYTHING ANYWAY",
  "ENSURE THAT YOUR LIFE STAYS IN FLUX",
  "EVEN YOUR FAMILY CAN BETRAY YOU",
  "EVERY ACHIEVEMENT REQUIRES A SACRIFICE",
  "REDISTRIBUTING WEALTH IS IMPERATIVE",
  "RELATIVITY IS NO BOON TO MANKIND",
  "RELIGION CAUSES AS MANY PROBLEMS AS IT SOLVES",
  "REMEMBER YOU ALWAYS HAVE FREEDOM OF CHOICE",
  "REPETITION IS THE BEST WAY TO LEARN",
  "RESOLUTIONS SERVE TO EASE OUR CONSCIENCE",
  "REVOLUTION BEGINS WITH CHANGES IN THE INDIVIDUAL",
  "ROMANTIC LOVE WAS INVENTED TO MANIPULATE WOMEN",
  "ROUTINE IS A LINK WITH THE PAST",
  "ROUTINE SMALL EXCESSES ARE WORSE THAN THEN THE OCCASIONAL DEBAUCH",
  "SACRIFICING YOURSELF FOR A BAD CAUSE IS NOT A MORAL ACT",
  "SALVATION CAN'T BE BOUGHT AND SOLD",
  "SELF-AWARENESS CAN BE CRIPPLING",
  "SELF-CONTEMPT CAN DO MORE HARM THAN GOOD",
  "SELFISHNESS IS THE MOST BASIC MOTIVATION",
  "SELFLESSNESS IS THE HIGHEST ACHIEVEMENT",
  "SEPARATISM IS THE WAY TO A NEW BEGINNING",
  "SEX DIFFERENCES ARE HERE TO STAY",
  "SIN IS A MEANS OF SOCIAL CONTROL",
  "SLIPPING INTO MADNESS IS GOOD FOR THE SAKE OF COMPARISON",
  "SLOPPY THINKING GETS WORSE OVER TIME",
  "SOLITUDE IS ENRICHING",
  "SOMETIMES SCIENCE ADVANCES FASTER THAN IT SHOULD",
  "SOMETIMES THINGS SEEM TO HAPPEN OF THEIR OWN ACCORD",
  "SPENDING TOO MUCH TIME ON SELF-IMPROVEMENT IS ANTISOCIAL",
  // add more aphorisms here
];
