const express = require("express");
const app = express();
const PORT = process.env.PORT || 3000;

// List of AI-generated aphorisms inspired by Jenny Holzer
const aphorisms = [
  "A LITTLE KNOWLEDGE CAN GO A LONG WAY",
  "A LOT OF PROFESSIONALS ARE CRACKPOTS",
  "A MAN CAN'T KNOW WHAT IT IS TO BE A MOTHER",
  "A NAME MEANS A LOT JUST BY ITSELF",
  "A POSITIVE ATTITUDE MEANS ALL THE DIFFERENCE IN THE WORLD",
  "A RELAXED MAN IS NOT NECESSARILY A BETTER MAN",
  "A SENSE OF TIMING IS THE MARK OF GENIUS",
  "A SINCERE EFFORT IS ALL YOU CAN ASK",
  "A SINGLE EVENT CAN HAVE INFINITELY MANY INTERPRETATIONS",
  "A SOLID HOME BASE BUILDS A SENSE OF SELF",
  "A STRONG SENSE OF DUTY IMPRISONS YOU",
  "ABSOLUTE SUBMISSION CAN BE A FORM OF FREEDOM",
  "ABSTRACTION IS A TYPE OF DECADENCE",
  "ABUSE OF POWER COMES AS NO SURPRISE",
  "ACTION CAUSES MORE TROUBLE THAN THOUGHT",
  "ALIENATION PRODUCES ECCENTRICS OR REVOLUTIONARIES",
  "ALL THINGS ARE DELICATELY INTERCONNECTED",
  "AMBITION IS JUST AS DANGEROUS AS COMPLACENCY",
  "AMBIVALENCE CAN RUIN YOUR LIFE",
  "AN ELITE IS INEVITABLE",
  "ANGER OR HATE CAN BE A USEFUL MOTIVATING FORCE",
  "ANIMALISM IS PERFECTLY HEALTHY",
  "ANY SURPLUS IS IMMORAL",
  "ANYTHING IS A LEGITIMATE AREA OF INVESTIGATION",
  "ARTIFICIAL DESIRES ARE DESPOILING THE EARTH",
  "AT TIMES INACTIVITY IS PREFERABLE TO MINDLESS FUNCTIONING",
  "AT TIMES YOUR UNCONSCIOUSNESS IS TRUER THAN YOUR CONSCIOUS MIND",
  "AUTOMATION IS DEADLY",
  "AWFUL PUNISHMENT AWAITS REALLY BAD PEOPLE",
  "BAD INTENTIONS CAN YIELD GOOD RESULTS",
  "BEING ALONE WITH YOURSELF IS INCREASINGLY UNPOPULAR",
  "BEING HAPPY IS MORE IMPORTANT THAN ANYTHING ELSE",
  "BEING JUDGMENTAL IS A SIGN OF LIFE",
  "BEING SURE OF YOURSELF MEANS YOU'RE A FOOL",
  "BELIEVING IN REBIRTH IS THE SAME AS ADMITTING DEFEAT",
  "BOREDOM MAKES YOU DO CRAZY THINGS",
  "CALM IS MORE CONDUCTIVE TO CREATIVITY THAN IS ANXIETY",
  "CATEGORIZING FEAR IS CALMING",
  "CHANGE IS VALUABLE WHEN THE OPPRESSED BECOME TYRANTS",
  "CHASING THE NEW IS DANGEROUS TO SOCIETY",
  "CHILDREN ARE THE MOST CRUEL OF ALL",
  "CHILDREN ARE THE HOPE OF THE FUTURE",
  "CLASS ACTION IS A NICE IDEA WITH NO SUBSTANCE",
  "CLASS STRUCTURE IS AS ARTIFICIAL AS PLASTIC",
  "CONFUSING YOURSELF IS A WAY TO STAY HONEST",
  "CRIME AGAINST PROPERTY IS RELATIVELY UNIMPORTANT",
  "DECADENCE CAN BE AN END IN ITSELF",
  "DECENCY IS A RELATIVE THING",
  "DEPENDENCE CAN BE A MEAL TICKET",
  "DESCRIPTION IS MORE IMPORTANT THAN METAPHOR",
  "DEVIANTS ARE SACRIFICED TO INCREASE GROUP SOLIDARITY",
  "DISGUST IS THE APPROPRIATE RESPONSE TO MOST SITUATIONS",
  "DISORGANIZATION IS A KIND OF ANESTHESIA",
  "DON'T PLACE TOO MUCH TRUST IN EXPERTS",
  "DRAMA OFTEN OBSCURES THE REAL ISSUES",
  "DREAMING WHILE AWAKE IS A FRIGHTENING CONTRADICTION",
  "DYING AND COMING BACK GIVES YOU CONSIDERABLE PERSPECTIVE",
  "DYING SHOULD BE EASY AS FALLING OFF A LOG",
  "EATING TOO MUCH IS CRIMINAL",
  "ELABORATION IS A FORM OF POLLUTION",
  "EMOTIONAL RESPONSES ARE AS VALUABLE AS INTELLECTUAL RESPONSES",
  "ENJOY YOURSELF BECAUSE YOU CAN'T CHANGE ANYTHING ANYWAY",
  "ENSURE THAT YOUR LIFE STAYS IN FLUX",
  "EVEN YOUR FAMILY CAN BETRAY YOU",
  "EVERY ACHIEVEMENT REQUIRES A SACRIFICE",
  // add more aphorisms here
];

// Endpoint to serve a random aphorism
app.get("/aphorism", (req, res) => {
  const randomIndex = Math.floor(Math.random() * aphorisms.length);
  const randomAphorism = aphorisms[randomIndex];
  res.json({ aphorism: randomAphorism });
});

// Start the server
app.listen(PORT, () => {
  console.log(`Server is running on http://localhost:${PORT}`);
});
